#!/bin/bash

# Quick Start Guide for HR Portal

echo "=========================================="
echo "  HR Recruitment Portal - Quick Start"
echo "=========================================="
echo ""

# Check if Django is running
if ! curl -s http://127.0.0.1:8000/ > /dev/null 2>&1; then
    echo "⚠️  Django server is not running!"
    echo "Start the server with: python manage.py runserver"
    exit 1
fi

echo "✅ Django server is running!"
echo ""
echo "=========================================="
echo "  Quick Links"
echo "=========================================="
echo ""
echo "🎓 Student Portal:"
echo "   Register: http://127.0.0.1:8000/register/"
echo "   Login:    http://127.0.0.1:8000/login/"
echo ""
echo "💼 HR Portal:"
echo "   Login:    http://127.0.0.1:8000/hr/login/"
echo "   Register: http://127.0.0.1:8000/hr/register/"
echo ""
echo "⚙️  Admin Panel:"
echo "   URL:      http://127.0.0.1:8000/admin/"
echo ""
echo "=========================================="
echo "  Test Credentials"
echo "=========================================="
echo ""
echo "HR Account:"
echo "  Username: hr_admin"
echo "  Password: hr123456"
echo ""
echo "=========================================="
echo "  First Time Setup"
echo "=========================================="
echo ""
echo "1. Create superuser:"
echo "   python manage.py createsuperuser"
echo ""
echo "2. Access admin panel to create test students"
echo ""
echo "3. Have students register and complete their profiles"
echo ""
echo "4. Login as HR to see students and filter them"
echo ""
echo "=========================================="
echo ""
echo "For detailed information, see README.md"
echo "For implementation details, see HR_IMPLEMENTATION.md"
echo ""
