# Generated by Django 6.0 on 2025-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userprofile_date_of_birth_userprofile_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="admission_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="backlogs",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="certifications_links",
            field=models.TextField(
                blank=True, help_text="Paste certification links, one per line"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_backlogs",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="hackerrank_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="other_platforms",
            field=models.TextField(
                blank=True,
                help_text="Other platform usernames (e.g., Codeforces: username, LeetCode: username)",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="year_of_study",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                    ("5", "Fifth Year"),
                ],
                max_length=20,
            ),
        ),
    ]
