# Generated by Django 6.0 on 2025-12-23 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_emailotp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hrprofile",
            name="approval_requested_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="hrprofile",
            name="approval_token",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="hrprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hrprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_hr_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="hrprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="HR account approved by admin"
            ),
        ),
        migrations.AddField(
            model_name="hrprofile",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection if applicable"
            ),
        ),
    ]
