# Generated by Django 6.0 on 2025-12-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_hrprofile_approval_requested_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrprofile",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Notes/message for admin from HR applicant"
            ),
        ),
    ]
