# Generated by Django 6.0 on 2025-12-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_hrprofile_admin_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="otp",
            field=models.CharField(max_length=255),
        ),
    ]
