# Generated by Django 6.0 on 2025-12-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_emailotp_failed_attempts_alter_emailotp_otp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailotp",
            options={"verbose_name": "Email OTP", "verbose_name_plural": "Email OTPs"},
        ),
        migrations.AddField(
            model_name="emailotp",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="last_request_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="request_count",
            field=models.IntegerField(default=0),
        ),
    ]
