# Generated by Django 6.0 on 2025-12-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_emailotp_options_emailotp_last_attempt_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("endpoint", models.CharField(default="otp_verify", max_length=100)),
                ("attempt_count", models.IntegerField(default=0)),
                ("first_attempt_at", models.DateTimeField(auto_now_add=True)),
                ("last_attempt_at", models.DateTimeField(auto_now=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IP Rate Limit",
                "verbose_name_plural": "IP Rate Limits",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "endpoint"],
                        name="core_iprate_ip_addr_05b7c4_idx",
                    )
                ],
                "unique_together": {("ip_address", "endpoint")},
            },
        ),
    ]
