# Generated by Django 5.1.15 on 2026-03-18 10:16

import core.file_validators
import core.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_ipratelimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="PDF, JPG, or PNG - max 5 MB",
                storage=storages.backends.s3.S3Storage(location="media"),
                upload_to=core.models.document_path,
                validators=[core.file_validators.validate_document_file],
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="hrprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ipratelimit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                help_text="JPG or PNG, max 1 MB",
                null=True,
                storage=storages.backends.s3.S3Storage(location="media"),
                upload_to=core.models.profile_photo_path,
                validators=[core.file_validators.validate_profile_photo],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="PDF only, max 5 MB",
                null=True,
                storage=storages.backends.s3.S3Storage(location="media"),
                upload_to=core.models.resume_path,
                validators=[core.file_validators.validate_resume_file],
            ),
        ),
    ]
